spring.application.name=SpringBootRestProj09-ActorAPI-MiniProject




#server.port
server.port=4041

#context path
server.servlet.context.path="/RestActorProj
#Datasource cfgs
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql:///nutan
spring.datasource.username=root
spring.datasource.password=nutan
 
 
#Hibernate -JPA properties
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true